"""La zone annexe de md2latex.py, vue echouer et vue passer.

Regle G0.5 de la v1, reprise par `tests/portes/socle.py` : « un controle qu'on
n'a jamais vu echouer n'est pas un controle ». Une fonctionnalite non plus.

CE QUI EST EN JEU. L'appel PoPETs 2027 limite le CORPS a 12 pages et exclut du
decompte « any clearly-marked appendices », la bibliographie, les
remerciements et les trois sections obligatoires. Avant la zone annexe, une
section d'annexe ecrite dans le manuscrit tombait dans la zone
GENERATED:BODY -- donc DANS les 12 pages, l'inverse du but recherche
(`resultats/decision-pagination-2026-09-13.md` §2).

CE QUE CES TESTS MONTRENT, mecaniquement et sans compiler :
  - `test_echec_sans_zone_annexe_le_contenu_tombe_dans_le_corps` reproduit le
    defaut d'origine et le voit echouer sur le convertisseur d'avant (voir
    plus bas, « COMMENT ON L'A VU ECHOUER ») ;
  - `test_passage_apres_le_marqueur_hors_du_corps` : ce qui suit `## Appendix`
    est en zone APPENDIX et **pas** en zone BODY ;
  - `test_passage_avant_le_marqueur_dans_le_corps` : ce qui precede le
    marqueur est bien en zone BODY -- sans quoi le test precedent serait
    satisfait par un convertisseur qui perd purement et simplement du texte ;
  - les sections imposees par le gabarit ne sont pas capturables par le
    marqueur, et rien ne se perd en route.

COMMENT ON L'A VU ECHOUER (trace reelle, pas supposee). Ces tests s'executent
contre un convertisseur passe en parametre par la variable d'environnement
`MD2LATEX` ; lances contre la version d'avant la zone annexe --

    git show 2e88025:article/latex/md2latex.py > /tmp/md2latex-avant.py
    MD2LATEX=/tmp/md2latex-avant.py python3 -m unittest test_md2latex_annexe

-- les deux tests `test_echec_*` et `test_passage_apres_*` echouent : le texte
d'annexe est retrouve dans la zone BODY. C'est ce que la zone annexe corrige.

Ces tests n'ecrivent que dans un repertoire temporaire.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

RACINE = Path(__file__).resolve().parents[2]
MD2LATEX = Path(os.environ.get("MD2LATEX", RACINE / "article" / "latex" / "md2latex.py"))

# Deux phrases-temoins uniques, cherchees ensuite dans les zones generees.
TEMOIN_CORPS = "PHRASE TEMOIN DU CORPS, comptee dans les douze pages."
TEMOIN_ANNEXE = "PHRASE TEMOIN DE L ANNEXE, hors du decompte des douze pages."

# Le convertisseur exige au moins une figure (sync_figures s'arrete sinon) :
# un PNG 1x1 valide suffit, il n'est jamais rendu ici.
PNG_1x1 = bytes.fromhex(
    "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4"
    "890000000a49444154789c6360000002000100fbc8bd0f0000000049454e44ae426082"
)

MAIN_TEX_SQUELETTE = """\\documentclass[sigconf]{acmart}
\\begin{document}
\\title[Court]{Titre complet}
\\begin{abstract}
% === GENERATED:ABSTRACT BEGIN (auto -- regenerated by md2latex.py, do not hand-edit) ===
% === GENERATED:ABSTRACT END ===
\\end{abstract}
\\maketitle
% === GENERATED:BODY BEGIN (auto -- regenerated by md2latex.py, do not hand-edit) ===
% === GENERATED:BODY END ===
\\appendix
% === GENERATED:APPENDIX BEGIN (auto -- regenerated by md2latex.py, do not hand-edit) ===
% === GENERATED:APPENDIX END ===
% === GENERATED:BACKMATTER BEGIN (auto -- regenerated by md2latex.py, do not hand-edit) ===
% === GENERATED:BACKMATTER END ===
\\end{document}
"""

# Manuscrit minimal mais representatif : un resume, une section de corps, une
# figure (exigee par sync_figures), les trois sections obligatoires, une
# annexe, et la bibliographie en fermeture.
MANUSCRIT = """# Titre complet: sous-titre

## Abstract

Resume de controle.

## 1. Introduction

{corps}

> **Figure 1 -- Legende de controle.** Data: aucune.

{annexe_bloc}

## 8. Ethics Considerations

Section obligatoire, hors decompte.

## 9. Availability

Section obligatoire, hors decompte.

## 10. AI Use

Section obligatoire, hors decompte.

## References

[1] Rien.
"""

BLOC_ANNEXE = """## Appendix

## Threshold census

{annexe}
"""

BLOC_SANS_MARQUEUR = """## Threshold census

{annexe}
"""


# Depuis le 13/09/2026, md2latex.py lit le manuscrit A TRAVERS
# outils/rendu_registre.py (§1.3). Un depot jetable doit donc porter la machine
# du registre, sinon le convertisseur s'arrete -- ce qui est le comportement
# voulu, et ce que teste test_md2latex_registre.py.
REGISTRE_MINIMAL = (
    "id,grandeur,valeur,ic_bas,ic_haut,methode_ic,n_replicats,graine,script,"
    "commit,csv_source,statut\n"
    "temoin-ok,\"Grandeur de controle\",42.0,41.0,43.0,bootstrap,10,1,"
    "analyses/temoin.py,abcdef0,resultats/temoin.csv,courant\n"
    "temoin-retracte,\"Grandeur de controle RETRACTEE, remplacee par "
    "temoin-ok\",13.0,12.0,14.0,bootstrap,10,1,analyses/temoin.py,abcdef0,"
    "resultats/temoin.csv,retracte\n"
)


def installe_machine_registre(racine: Path) -> None:
    """Recopie outils/rendu_registre.py, ses portes, et un registre minimal."""
    (racine / "outils" / "portes").mkdir(parents=True, exist_ok=True)
    shutil.copyfile(RACINE / "outils" / "rendu_registre.py",
                    racine / "outils" / "rendu_registre.py")
    for nom in ("registre_chiffres.py", "commun.py"):
        shutil.copyfile(RACINE / "outils" / "portes" / nom,
                        racine / "outils" / "portes" / nom)
    (racine / "resultats").mkdir(parents=True, exist_ok=True)
    (racine / "resultats" / "registre-chiffres.csv").write_text(
        REGISTRE_MINIMAL, encoding="utf-8")


def zones_generees(tmp: Path, annexe_bloc: str) -> dict[str, str]:
    """Fabrique une arborescence article/ jetable, lance le convertisseur, et
    renvoie le contenu de chaque zone GENERATED de main.tex."""
    installe_machine_registre(tmp)
    art = tmp / "article"
    (art / "latex").mkdir(parents=True)
    (art / "figures").mkdir()
    (art / "figures" / "fig1-monde-ouvert.png").write_bytes(PNG_1x1)
    (art / "references.bib").write_text("@misc{rien, title={Rien}}\n", encoding="utf-8")
    (art / "manuscrit.md").write_text(
        MANUSCRIT.format(corps=TEMOIN_CORPS,
                         annexe_bloc=annexe_bloc.format(annexe=TEMOIN_ANNEXE)),
        encoding="utf-8")
    (art / "latex" / "main.tex").write_text(MAIN_TEX_SQUELETTE, encoding="utf-8")
    cible = art / "latex" / "md2latex.py"
    shutil.copyfile(MD2LATEX, cible)

    res = subprocess.run([sys.executable, str(cible)],
                         capture_output=True, text=True, cwd=str(art / "latex"))
    if res.returncode != 0:
        raise AssertionError(
            "md2latex.py a echoue (code %d) :\n%s" % (res.returncode, res.stdout + res.stderr))

    tex = (art / "latex" / "main.tex").read_text(encoding="utf-8")
    zones = {}
    for nom in ("ABSTRACT", "BODY", "APPENDIX", "BACKMATTER"):
        motif = (r"% === GENERATED:" + nom + r" BEGIN[^\n]*===\n"
                 r"(.*?)% === GENERATED:" + nom + r" END ===")
        m = re.search(motif, tex, re.DOTALL)
        zones[nom] = m.group(1) if m else ""
    return zones


class TestZoneAnnexe(unittest.TestCase):

    def test_echec_sans_zone_annexe_le_contenu_tombe_dans_le_corps(self):
        """Le defaut d'origine, reproduit : sans marqueur, une section d'annexe
        est balayee dans le corps -- donc comptee dans les 12 pages."""
        with tempfile.TemporaryDirectory() as t:
            zones = zones_generees(Path(t), BLOC_SANS_MARQUEUR)
            self.assertIn(TEMOIN_ANNEXE, zones["BODY"],
                          "sans marqueur, le contenu doit rester dans le corps "
                          "(c'est le comportement d'avant, et il reste correct "
                          "en l'absence de marqueur)")
            self.assertEqual(zones["APPENDIX"].strip(), "",
                             "sans marqueur, la zone annexe doit rester vide")

    def test_passage_apres_le_marqueur_hors_du_corps(self):
        """Ce qui suit '## Appendix' sort du corps et va en annexe."""
        with tempfile.TemporaryDirectory() as t:
            zones = zones_generees(Path(t), BLOC_ANNEXE)
            self.assertNotIn(TEMOIN_ANNEXE, zones["BODY"],
                             "le contenu place apres le marqueur ne doit PAS "
                             "etre compte dans le corps")
            self.assertIn(TEMOIN_ANNEXE, zones["APPENDIX"],
                          "le contenu place apres le marqueur doit etre emis "
                          "en annexe")

    def test_passage_avant_le_marqueur_dans_le_corps(self):
        """Contre-epreuve indispensable : le test precedent serait satisfait
        par un convertisseur qui perd le texte. Ce qui precede le marqueur doit
        rester compte dans le corps."""
        with tempfile.TemporaryDirectory() as t:
            zones = zones_generees(Path(t), BLOC_ANNEXE)
            self.assertIn(TEMOIN_CORPS, zones["BODY"])
            self.assertNotIn(TEMOIN_CORPS, zones["APPENDIX"])

    def test_passage_le_marqueur_nemet_rien_lui_meme(self):
        """Le marqueur est une sentinelle, pas une section : aucun
        \\section{Appendix} ne doit apparaitre (LaTeX pose deja le titre des
        annexes en lettres)."""
        with tempfile.TemporaryDirectory() as t:
            zones = zones_generees(Path(t), BLOC_ANNEXE)
            self.assertNotIn("\\section{Appendix}", zones["APPENDIX"])
            self.assertNotIn("\\section{Appendix}", zones["BODY"])
            self.assertIn("\\section{Threshold census}", zones["APPENDIX"])

    def test_passage_sections_obligatoires_non_capturables(self):
        """Un marqueur place trop tot ne doit pas faire disparaitre une
        section que le gabarit exige : §8/§9/§10 partent en BACKMATTER meme
        posees apres le marqueur."""
        with tempfile.TemporaryDirectory() as t:
            zones = zones_generees(Path(t), BLOC_ANNEXE)
            for env in ("ethics", "openscience", "ai"):
                self.assertIn("\\begin{%s}" % env, zones["BACKMATTER"],
                              "la section obligatoire %s doit rester en "
                              "backmatter" % env)
                self.assertNotIn("\\begin{%s}" % env, zones["APPENDIX"])

    def test_passage_rien_ne_se_perd(self):
        """Aucune des deux phrases-temoins ne doit disparaitre du document,
        quelle que soit la presence du marqueur."""
        for bloc in (BLOC_ANNEXE, BLOC_SANS_MARQUEUR):
            with tempfile.TemporaryDirectory() as t:
                zones = zones_generees(Path(t), bloc)
                tout = "".join(zones.values())
                self.assertIn(TEMOIN_CORPS, tout)
                self.assertIn(TEMOIN_ANNEXE, tout)


if __name__ == "__main__":
    unittest.main()
